[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "reldiff"
version = "0.0.0"
authors = [
  { name="Valter Hudovernik", email="valter.hudovernik@gmail.com" },
]
description = "TODO"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "syntherela",
  "torch_geometric",
  "torch_ema",
  "wandb",
  "kaleido",
  "gdown",
  "relbench[full]",
  "tomli==2.0.1",
  "syntheval",
  "sentence-transformers==2.7.0"
]

[project.optional-dependencies]
qwen = [
  "torch==2.2.2",
  "torchvision==0.17.2",
  "torchaudio==2.2.2",
  "transformers==4.51.3",
  "tokenizers==0.21.1",
  "peft==0.15.2",
  "accelerate==1.6.0",
  "huggingface-hub==0.30.2"
]

[project.urls]
Homepage = "TODO"
Issues = "TODO"

[tool.setuptools.packages]
find = { "where" = ["src"] }
